# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-19 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nickname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
